# Generated by Django 5.0.1 on 2024-04-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_rename_notes_pipelinenotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('TW', 'This Week'), ('TODAY', 'Today'), ('TY', 'This Year'), ('TM', 'This Month')], default='TODAY', max_length=100),
        ),
    ]
