# Generated by Django 5.0.1 on 2024-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_target_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('TW', 'This Week'), ('TODAY', 'Today'), ('TM', 'This Month'), ('TY', 'This Year')], default='TODAY', max_length=100),
        ),
    ]
