# Generated by Django 5.0.1 on 2024-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_target_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('TODAY', 'Today'), ('TM', 'This Month'), ('TW', 'This Week'), ('TY', 'This Year')], default='TODAY', max_length=100),
        ),
    ]
