# Generated by Django 5.0.1 on 2024-04-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_alter_target_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('TM', 'This Month'), ('TY', 'This Year'), ('TODAY', 'Today'), ('TW', 'This Week')], default='TODAY', max_length=100),
        ),
    ]
