# Generated by Django 5.0.1 on 2024-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_alter_target_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('TM', 'This Month'), ('TW', 'This Week'), ('TODAY', 'Today'), ('TY', 'This Year')], default='TODAY', max_length=100),
        ),
    ]
