# Generated by Django 5.0.1 on 2024-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_alter_report_notes_alter_target_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
