# Generated by Django 5.0.1 on 2024-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_staff_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('This Week', 'This Week'), ('Today', 'Today'), ('This Year', 'This Year'), ('This Month', 'This Month')], default='TODAY', max_length=100),
        ),
    ]
