# Generated by Django 5.0.1 on 2024-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_alter_target_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('Today', 'Today'), ('This Year', 'This Year'), ('This Month', 'This Month'), ('This Week', 'This Week')], default='TODAY', max_length=100),
        ),
    ]
