# Generated by Django 5.0.1 on 2024-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_alter_target_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='timeline',
            field=models.CharField(choices=[('This Year', 'This Year'), ('This Month', 'This Month'), ('This Week', 'This Week'), ('Today', 'Today')], default='TODAY', max_length=100),
        ),
    ]
