# Generated by Django 5.0.1 on 2024-03-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('hot', 'hot'), ('warm', 'warm'), ('cold', 'cold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('face', 'face to face '), ('call', 'call')], max_length=70),
        ),
    ]
