# Generated by Django 5.0.1 on 2024-04-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_lead_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('warm', 'warm'), ('cold', 'cold'), ('hot', 'hot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('face', 'face to face '), ('chat', 'chat'), ('call', 'call')], max_length=70),
        ),
    ]
