# Generated by Django 5.0.1 on 2024-04-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_lead_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('warm', 'warm'), ('hot', 'hot'), ('cold', 'cold')], max_length=20),
        ),
    ]
