# Generated by Django 5.0.1 on 2024-04-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_lead_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='next_step_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('call', 'call'), ('face', 'face to face ')], max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='next_step_date',
            field=models.DateField(),
        ),
    ]
