# Generated by Django 5.0.1 on 2024-04-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_rename_date_added_interaction_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('warm', 'warm'), ('hot', 'hot')], max_length=20),
        ),
    ]
