# Generated by Django 5.0.1 on 2024-04-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_lead_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('hot', 'hot'), ('warm', 'warm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('face', 'face to face '), ('call', 'call')], max_length=70),
        ),
    ]
