# Generated by Django 5.0.1 on 2024-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_interaction_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('white', 'white '), ('light', 'light grey'), ('secondary', 'grey'), ('warning', 'yellow'), ('success', 'green '), ('danger', 'red'), ('dark', 'black'), ('info', 'sky blue '), ('primary', 'blue')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('hot', 'hot'), ('warm', 'warm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('white', 'white '), ('light', 'light grey'), ('secondary', 'grey'), ('warning', 'yellow'), ('success', 'green '), ('danger', 'red'), ('dark', 'black'), ('info', 'sky blue '), ('primary', 'blue')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('call', 'call'), ('face', 'face to face '), ('chat', 'chat')], max_length=70),
        ),
    ]
