# Generated by Django 5.0.1 on 2024-04-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_probableconversationoutcome_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('warm', 'warm'), ('hot', 'hot'), ('cold', 'cold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('danger', 'red'), ('info', 'sky blue '), ('primary', 'blue'), ('success', 'green '), ('dark', 'black'), ('white', 'white '), ('light', 'light grey'), ('warning', 'yellow'), ('secondary', 'grey')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('face', 'face to face '), ('call', 'call')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('danger', 'red'), ('info', 'sky blue '), ('primary', 'blue'), ('success', 'green '), ('dark', 'black'), ('white', 'white '), ('light', 'light grey'), ('warning', 'yellow'), ('secondary', 'grey')], default='primary', max_length=70),
        ),
    ]
