# Generated by Django 5.0.1 on 2024-04-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('warm', 'warm'), ('cold', 'cold'), ('hot', 'hot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('danger', 'red'), ('warning', 'yellow'), ('secondary', 'grey'), ('primary', 'blue'), ('dark', 'black'), ('white', 'white '), ('info', 'sky blue '), ('success', 'green ')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('call', 'call'), ('face', 'face to face '), ('chat', 'chat')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('danger', 'red'), ('warning', 'yellow'), ('secondary', 'grey'), ('primary', 'blue'), ('dark', 'black'), ('white', 'white '), ('info', 'sky blue '), ('success', 'green ')], default='primary', max_length=70),
        ),
    ]
