# Generated by Django 5.0.1 on 2024-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('hot', 'hot'), ('cold', 'cold'), ('warm', 'warm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('warning', 'yellow'), ('primary', 'blue'), ('info', 'sky blue '), ('dark', 'black'), ('white', 'white '), ('danger', 'red'), ('secondary', 'grey'), ('success', 'green ')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('call', 'call'), ('face', 'face to face ')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('warning', 'yellow'), ('primary', 'blue'), ('info', 'sky blue '), ('dark', 'black'), ('white', 'white '), ('danger', 'red'), ('secondary', 'grey'), ('success', 'green ')], default='primary', max_length=70),
        ),
    ]
