# Generated by Django 5.0.1 on 2024-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('warm', 'warm'), ('hot', 'hot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('secondary', 'grey'), ('dark', 'black'), ('primary', 'blue'), ('white', 'white '), ('warning', 'yellow'), ('danger', 'red'), ('info', 'sky blue '), ('success', 'green ')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('face', 'face to face '), ('call', 'call')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('secondary', 'grey'), ('dark', 'black'), ('primary', 'blue'), ('white', 'white '), ('warning', 'yellow'), ('danger', 'red'), ('info', 'sky blue '), ('success', 'green ')], default='primary', max_length=70),
        ),
    ]
