# Generated by Django 5.0.1 on 2024-04-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('white', 'white '), ('info', 'sky blue '), ('dark', 'black'), ('secondary', 'grey'), ('danger', 'red'), ('primary', 'blue'), ('success', 'green '), ('warning', 'yellow')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('face', 'face to face '), ('call', 'call'), ('chat', 'chat')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('white', 'white '), ('info', 'sky blue '), ('dark', 'black'), ('secondary', 'grey'), ('danger', 'red'), ('primary', 'blue'), ('success', 'green '), ('warning', 'yellow')], default='primary', max_length=70),
        ),
    ]
