# Generated by Django 5.0.1 on 2024-04-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('hot', 'hot'), ('warm', 'warm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('info', 'sky blue '), ('dark', 'black'), ('secondary', 'grey'), ('white', 'white '), ('danger', 'red'), ('primary', 'blue'), ('warning', 'yellow'), ('success', 'green ')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('face', 'face to face '), ('chat', 'chat'), ('call', 'call')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('info', 'sky blue '), ('dark', 'black'), ('secondary', 'grey'), ('white', 'white '), ('danger', 'red'), ('primary', 'blue'), ('warning', 'yellow'), ('success', 'green ')], default='primary', max_length=70),
        ),
    ]
