# Generated by Django 5.0.1 on 2024-04-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_product_product_price'),
        ('customers', '0019_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('warm', 'warm'), ('hot', 'hot'), ('cold', 'cold')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('success', 'green '), ('white', 'white '), ('dark', 'black'), ('info', 'sky blue '), ('warning', 'yellow'), ('danger', 'red'), ('primary', 'blue'), ('secondary', 'grey')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('face', 'face to face '), ('call', 'call')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('success', 'green '), ('white', 'white '), ('dark', 'black'), ('info', 'sky blue '), ('warning', 'yellow'), ('danger', 'red'), ('primary', 'blue'), ('secondary', 'grey')], default='primary', max_length=70),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(blank=True, to='company.product'),
        ),
    ]
