# Generated by Django 5.0.1 on 2024-04-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0020_alter_customer_lead_type_remove_customer_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('warm', 'warm'), ('hot', 'hot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('secondary', 'grey'), ('dark', 'black'), ('info', 'sky blue '), ('warning', 'yellow'), ('white', 'white '), ('danger', 'red'), ('success', 'green '), ('primary', 'blue')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('face', 'face to face '), ('call', 'call'), ('chat', 'chat')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('secondary', 'grey'), ('dark', 'black'), ('info', 'sky blue '), ('warning', 'yellow'), ('white', 'white '), ('danger', 'red'), ('success', 'green '), ('primary', 'blue')], default='primary', max_length=70),
        ),
    ]
