# Generated by Django 5.0.1 on 2024-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('hot', 'hot'), ('cold', 'cold'), ('warm', 'warm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('danger', 'red'), ('secondary', 'grey'), ('success', 'green '), ('dark', 'black'), ('warning', 'yellow'), ('info', 'sky blue '), ('white', 'white '), ('primary', 'blue')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('face', 'face to face '), ('chat', 'chat'), ('call', 'call')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('danger', 'red'), ('secondary', 'grey'), ('success', 'green '), ('dark', 'black'), ('warning', 'yellow'), ('info', 'sky blue '), ('white', 'white '), ('primary', 'blue')], default='primary', max_length=70),
        ),
    ]
