# Generated by Django 5.0.1 on 2024-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('hot', 'hot'), ('warm', 'warm'), ('cold', 'cold')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('secondary', 'grey'), ('info', 'sky blue '), ('danger', 'red'), ('white', 'white '), ('dark', 'black'), ('success', 'green '), ('primary', 'blue'), ('warning', 'yellow')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('chat', 'chat'), ('face', 'face to face '), ('call', 'call')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('secondary', 'grey'), ('info', 'sky blue '), ('danger', 'red'), ('white', 'white '), ('dark', 'black'), ('success', 'green '), ('primary', 'blue'), ('warning', 'yellow')], default='primary', max_length=70),
        ),
    ]
