# Generated by Django 5.0.1 on 2024-08-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_alter_customer_lead_type_alter_customerlabel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='lead_type',
            field=models.CharField(choices=[('cold', 'cold'), ('hot', 'hot'), ('warm', 'warm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlabel',
            name='colour',
            field=models.CharField(choices=[('warning', 'yellow'), ('white', 'white '), ('dark', 'black'), ('info', 'sky blue '), ('success', 'green '), ('danger', 'red'), ('secondary', 'grey'), ('primary', 'blue')], default='primary', max_length=70),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='conversation_method',
            field=models.CharField(choices=[('face', 'face to face '), ('call', 'call'), ('chat', 'chat')], max_length=70),
        ),
        migrations.AlterField(
            model_name='probableconversationoutcome',
            name='colour',
            field=models.CharField(choices=[('warning', 'yellow'), ('white', 'white '), ('dark', 'black'), ('info', 'sky blue '), ('success', 'green '), ('danger', 'red'), ('secondary', 'grey'), ('primary', 'blue')], default='primary', max_length=70),
        ),
    ]
